apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxhseu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boxhseu
  template:
    metadata:
      labels:
        app: boxhseu
    spec:
      containers:
      - image: okteto.dev/boxhseu:latest
        name: boxhseu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4d2ae90a-613e-497e-9af6-195eb0af056c"
        - name: Vless_Path
          value: "/4d2ae90a-613e-497e-9af6-195eb0af056c"
        - name: Vmess_UUID
          value: "ee29b315-19e2-4de1-aeb8-9e20d19e16cd"
        - name: Vmess_Path
          value: "/ee29b315-19e2-4de1-aeb8-9e20d19e16cd"
        - name: Share_Path
          value: "/v2link"
